package Pacman.Model.MapBlocks;

import Pacman.Model.MapBlock;

/**
 * Represents dots on the map, that can be eaten by player in order to score.
 */
public final class Dot extends MapBlock {
	/**
	 * Generated by eclipse
	 */
	private static final long serialVersionUID = -2455463933177430250L;
	
	/**
	 * to make this a singleton class
	 */
	protected static Dot instance;

	/**
	 * @return Instance of this class. 
	 */
	public static Dot getInstance() {
		if (instance == null) {
			instance = new Dot();
		}
		return instance;
	}

	/**
	 * @return {@code false}
	 */
	@Override
		public boolean canCollide() {
			return false;
		}

	/**
	 * @return {@code true}
	 */
	@Override
		public boolean isEatable() {
			return true;
		}
}
