package Pacman.Model.MapBlocks;

import Pacman.Model.MapBlock;
import Pacman.lib.Vector;

/**
 * Represents Walls on the map, that can not be overcome by ghosts and player.
 */
public final class Wall extends MapBlock {
	/**
	 * Generated by eclipse
	 */
	private static final long serialVersionUID = 4245203201493061340L;
	
	/**
	 * to make this a singleton class
	 */
	protected static Wall instance;
	
	/**
	 * @return Instance of this class. 
	 */
	public static Wall getInstance() {
		if (instance == null) {
			instance = new Wall();
		}
		return instance;
	}

	/**
	 * @return {@code true}
	 */
    @Override
    public boolean canCollide() {
        return true;
    }
    
    /**
	 * @return {@code false}
	 */
    public boolean eat(Vector position) {
        return false;
    }
}
